### ISSUE TITLE
I can't get nnls-chroma to work while importing autochord

### ISSUE THREAD

**Issue by ARDEACT** [cjbayron/autochord#1]
When I import autochord, I get an error that says, "Vamp plugin has not been installed correctly" Says to put C:\Users\[user]\.conda\envs\ldm\lib\site-packages\autochord\res\nnls-chroma.so to vamp plugin folder, which doesn't exist, so I put it in the Vamp library folder in my conda env packages but that didn't work either. Any help?

**Comment by cjbayron** [comment]
@ARDEACT seems two things need to be addressed here.

1) is ensuring the VAMP plugin (`nnls-chroma.so`) is in the paths where `vampy-host` library tries to find it. you can know these paths by running:
```
import vamp
vamp.vampyhost.get_plugin_path()
```
you should put the plugin in at least one of the printed paths, if any

2) and **much more important** than no. 1, you're setting up in Windows (it seems) but `*.so` kind of plugin is intended for Linux (and yeah, I failed to indicate this in README).

what you'd probably need is the `*.dll` version of NNLS-chroma plugin ([reference](https://www.vamp-plugins.org/download.html?search=key&go=Go&platform=win32) regarding the plugin file types). But even with the DLL file, the source code is [hardcoded](https://github.com/cjbayron/autochord/blob/76976729dcc11d8af3dc421283168f153f124e91/src/autochord/__init__.py#L15) to load the `.so` file. so you may either try to fix it by cloning the repo and re-installing the modified version on your Windows machine, hopefully it works (and if you don't mind please submit a PR :pray: ) or I can try to fix it during my free time (probably on the weekend)

**Comment by cjbayron** [comment]
@ARDEACT I'm marking Windows as unsupported as of this moment. There are compatibility issues that arise with Windows, in particular:

1. The VAMP plugin `*.dll` for Windows is 32-bit. The Python library `vampy`/`vampyhost` is only able to load 32-bit plugins on a 32-bit Python installation.
2. TensorFlow, which is a core dependency of `autochord`, has no support for 32-bit.

Hence, Windows can't be supported as of now, unfortunately.

**Comment by xhocquet** [comment]
Edit: Nevermind! Crossed my wires 😓
