### ISSUE TITLE
How to run on OSX

### ISSUE THREAD

**Issue by xstasi** [cjbayron/autochord#2]
Hi!

I know your project is only meant to be supported on Linux, but I got it running on Mac OSX (with m2 architecture!) and I'd like to share how I did it.

Feel free to make of this information what you wish.

-----

1. Install dependencies
   * `brew install boost vamp-plugin-sdk`
2. Download nnls-chroma plugin
   * `git clone https://github.com/c4dm/nnls-chroma; cd nnls-chroma`
3. Make the dependencies available in the source tree (edit version accordingly)
   * `ln -s /opt/homebrew/Cellar/vamp-plugin-sdk/2.10.0/ vamp`
   * `ln -s /opt/homebrew/Cellar/boost/1.81.0_1 boost`
4. Horribly copy files around to be where the Makefile expects them
   * `cp vamp/lib/*a vamp/include/`
5. Patch Makefile.osx as follows
```
diff --git a/Makefile.osx b/Makefile.osx
index d6fa701..46839a3 100644
--- a/Makefile.osx
+++ b/Makefile.osx
@@ -1,9 +1,9 @@

-VAMP_SDK_DIR = ../vamp-plugin-sdk
+VAMP_SDK_DIR = vamp/include

-BOOST_ROOT = ../boost_1_48_0
+BOOST_ROOT = boost/include

-ARCHFLAGS ?= -mmacosx-version-min=10.7 -arch x86_64
+ARCHFLAGS ?= -mmacosx-version-min=10.7
 OPTFLAGS  ?= -O3 -ffast-math
 PLUGIN_EXT = .dylib
```
6. Build and install
   * `make -f Makefile.osx`
   * `mkdir -p ~/Library/Audio/Plug-Ins/Vamp`
   * `cp nnls-chroma.dylib ~/Library/Audio/Plug-Ins/Vamp`

-------

Hope this may save a bit of time and headache to the next person trying to run this :)

Thanks for your work!

**Comment by cjbayron** [comment]
@xstasi this is awesome! thanks for this information, I've linked this in [README](https://github.com/cjbayron/autochord#supported-environments)

**Comment by xgreenspace** [comment]
@xstasi Thank you so much! You made my life so much easier!

**Comment by rafaelcanovas** [comment]
Thank you very much, worked like a charm ✅

**Comment by nic519** [comment]
Can Apple silicon computers be used?

**Comment by aseyedia** [comment]
This worked! Just a reminder though to edit this line `ln -s /opt/homebrew/Cellar/boost/1.xx boost`  to be up-to-date with whatever version of Cellar happens to be current. Thank you!

**Comment by domcross** [comment]
My setup: MacOS 12.7 / Monterey, Apple Silicon M1 (Macbook Pro), vamp-plugin-sdk 2.10.0, boost 1.84.0 (latest available by brew). I am getting compile errors in the boost library:

- expected '(' for function-style cast or type construction
- expected ';' at end of declaration list
- expected ';' at end of declaration
- C++ requires a type specifier for all declarations

Probably just a compiler flag/setting wrong or missing, but I am lacking the right keywords to google a solution.
By chance anyone here has a good tip for me?

**Comment by dewijones92** [comment]
@domcross  try this docker method https://github.com/cjbayron/autochord/pull/9
