### ISSUE TITLE
How to train autochord?

### ISSUE THREAD

**Issue by xstasi** [cjbayron/autochord#4]
Hello there, and thanks again for the work!

I was wondering if it would be possible to run some training on the model in order to possibly increase the accuracy.

Would it be possible to know what data set you used and how?

Thanks!

**Comment by cjbayron** [comment]
hello @xstasi, the model was actually trained by using [this notebook](https://github.com/cjbayron/autochord/blob/main/model-development/train_seq.ipynb), which I've run using Google Colab. Unfortunately I won't be able to run through everything step-by-step but this should be a starting point. I haven't run it in a while so I'm not so sure if it's still compatible with Colab but I've used these [versions](https://github.com/cjbayron/autochord/blob/dd6033db91114c4a415c679a52fbd48000dcedd1/setup.py#L9-L15) of its dependencies.

The latest trained model is publicly available in [Google Drive](https://drive.google.com/drive/folders/1KoFYcKhmN1y_cyoC0KNH2ZLOpz_sCIXo?usp=sharing) and the data used to train are actually pre-extracted chroma vectors from this [research initiative](https://ddmal.music.mcgill.ca/research/The_McGill_Billboard_Project_(Chord_Analysis_Dataset)/) (see Audio Features section).

And btw, I presented this library in ISMIR2021 LBD session, for which I created this [paper](https://archives.ismir.net/ismir2021/latebreaking/000008.pdf) which you may also refer if you'd like to know more details :)

**Comment by xstasi** [comment]
Thanks!
